name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout your code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Cypress tests using official action
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:run

      # Merge JSON reports
      - name: Merge reports
        run: npm run merge:reports

      # Generate single HTML report
      - name: Generate HTML report
        run: npm run generate:report

      # Upload combined report
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports/

      # Upload screenshots
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/

      # Upload videos
      - name: Upload videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/
