name: Cypress Automation

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cypress-run:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: npm test

      - name: Upload Mochawesome Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome-Report
          path: cypress/reports

      - name: Upload Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Cypress-Videos
          path: cypress/videos

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Cypress-Screenshots
          path: cypress/screenshots